name: laqueadura_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  youtube_player_flutter: ^9.0.3
  intl: ^0.20.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_app_main.png"


flutter:
  uses-material-design: true

  assets:
    - assets/menu_1.png
    - assets/menu_2.png
    - assets/menu_3.png
    - assets/menu_4.png
    - assets/menu_5.png
    - assets/menu_6.png
    - assets/menu_7.png
    - assets/menu_8.png
    - assets/menu_11.png
    - assets/menu_22.png
    - assets/menu_33.png
    - assets/menu_44.png
    - assets/menu_55.png
    # - assets/menu_66.png
    # - assets/menu_77.png
    # - assets/menu_88.png
    - assets/icon_app.png
    - assets/icon_app_main.png
    - assets/video.png
    - assets/operativeCare/plastic.png
    - assets/operativeCare/surgery.png
    - assets/laws/family.png
    - assets/laws/pdf.png
    - assets/laws/L9263.pdf
    - assets/laws/L14443.pdf
    - assets/laws/sei.pdf
    - assets/icons_conscious_decision/adesivo.png
    - assets/icons_conscious_decision/anel_vaginal.png
    - assets/icons_conscious_decision/anticonc.png
    - assets/icons_conscious_decision/camisinha.png
    - assets/icons_conscious_decision/diu.png
    - assets/icons_conscious_decision/implanon2.png
    - assets/icons_conscious_decision/injeção.png
    - assets/icons_conscious_decision/laque.png
    - assets/icons_conscious_decision/male-gender.png
    - assets/icons_conscious_decision/femenine.png



  fonts:
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf

    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf

    - family: Aprila
      fonts:
        - asset: assets/fonts/aprila/Aprila-SemiBold.otf 
        - asset: assets/fonts/aprila/Aprila-Regular.otf 
        - asset: assets/fonts/aprila/Aprila-Medium.otf 
        - asset: assets/fonts/aprila/Aprila-Light.otf 
        - asset: assets/fonts/aprila/Aprila-ExtraBold.otf 
        - asset: assets/fonts/aprila/Aprila-Bold.otf
        - asset: assets/fonts/aprila/Aprila-Black.otf




























